import RestrictedPolynomials.Minors
import RestrictedPolynomials.Kronecker
import Mathlib.RingTheory.Polynomial.GaussLemma
import Mathlib.RingTheory.Localization.Integral
import Mathlib.RingTheory.UniqueFactorizationDomain.NormalizedFactors
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Polynomial.Tower
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# The ideal of minors (Lemmas 5.5 and 5.6, and the start of Section 5.3)

Let `I ⊆ ℚ[z]` be the ideal generated by all `ℓ × ℓ` minors `Δ(M_S)` of `A_{ℓ,∞}(z)`.
* Since `ℚ[z]` is Noetherian (indeed a PID), `I` is generated by finitely many minors.
* Its monic generator `D` lies in `ℤ[z]`, since it divides the monic minor with rows
  `2, 3, …, ℓ + 1` (Lemma 5.7 and Gauss's lemma), and every minor is `D · H` in `ℤ[z]`.
* Bézout's identity, after clearing denominators, gives `∑ V_S H_S = N` with `0 ≠ N ∈ ℤ`.
* Every root of `D` is `0` or a root of unity (Lemma 5.4), so `D ∣ (z (z^L - 1))^e` in `ℤ[z]`.

The last item is proved by adjoining to `ℚ` a root of each irreducible factor of `D`, which
gives a number field in which Lemma 5.4 applies.
-/

open Finset Polynomial

noncomputable section

namespace RestrictedPolynomials

variable {ℓ : ℕ}

/-- The rows `2, 3, …, ℓ + 1`. -/
def stdRows (ℓ : ℕ) : Fin ℓ → ℕ := fun r => (r : ℕ) + 2

lemma stdRows_admissible : Admissible (stdRows ℓ) :=
  ⟨fun r r' h => Fin.ext (by simpa [stdRows] using h), fun r => by simp [stdRows]⟩

lemma minor_stdRows_monic : (minor ℓ (stdRows ℓ)).Monic :=
  minor_monic _ (fun r r' h => by simpa [stdRows] using h) fun r => by simp [stdRows]

/-- The map `ℤ[z] → ℚ[z]`. -/
abbrev toQ : ℤ[X] →+* ℚ[X] := mapRingHom (Int.castRingHom ℚ)

lemma toQ_apply (f : ℤ[X]) : toQ f = f.map (Int.castRingHom ℚ) := rfl

lemma toQ_injective : Function.Injective toQ :=
  map_injective _ (RingHom.injective_int (Int.castRingHom ℚ))

lemma toQ_C (d : ℤ) : toQ (C d) = C (d : ℚ) := by simp

/-- Divisibility by a monic polynomial descends from `ℚ[z]` to `ℤ[z]`. -/
lemma dvd_of_toQ_dvd {g f : ℤ[X]} (hg : g.Monic) (h : toQ g ∣ toQ f) : g ∣ f := by
  rw [← modByMonic_eq_zero_iff_dvd hg]
  apply toQ_injective
  rw [toQ_apply, map_modByMonic _ hg, map_zero]
  exact (modByMonic_eq_zero_iff_dvd (hg.map _)).2 h

/-- Clearing the denominators of finitely many polynomials over `ℚ`. -/
lemma exists_common_denom {ι : Type*} (s : Finset ι) (u : ι → ℚ[X]) :
    ∃ d : ℤ, d ≠ 0 ∧ ∀ i ∈ s, ∃ v : ℤ[X], toQ v = C (d : ℚ) * u i := by
  classical
  induction s using Finset.induction_on with
  | empty => exact ⟨1, one_ne_zero, fun i hi => absurd hi (notMem_empty i)⟩
  | insert a s ha ih =>
    obtain ⟨d, hd, hv⟩ := ih
    obtain ⟨b, hb, hbv⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors ℤ) (u a)
    have hb0 : b ≠ 0 := nonZeroDivisors.ne_zero hb
    have hbv' : toQ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) (u a)) =
        C (b : ℚ) * u a := by
      rw [toQ_apply, ← algebraMap_int_eq, hbv, zsmul_eq_mul, ← C_eq_intCast]
    refine ⟨d * b, mul_ne_zero hd hb0, fun i hi => ?_⟩
    rcases mem_insert.1 hi with rfl | hi
    · refine ⟨C d * IsLocalization.integerNormalization (nonZeroDivisors ℤ) (u i), ?_⟩
      rw [map_mul, hbv', toQ_C]
      push_cast
      rw [C_mul]
      ring
    · obtain ⟨v, hv⟩ := hv i hi
      refine ⟨C b * v, ?_⟩
      rw [map_mul, hv, toQ_C]
      push_cast
      rw [C_mul]
      ring

/-- A product of elements dividing `F` divides a power of `F`. -/
lemma multiset_prod_dvd_pow {R : Type*} [CommMonoid R] (F : R) (s : Multiset R)
    (h : ∀ x ∈ s, x ∣ F) : s.prod ∣ F ^ Multiset.card s := by
  induction s using Multiset.induction_on with
  | empty => simp
  | cons a s ih =>
    rw [Multiset.prod_cons, Multiset.card_cons, pow_succ']
    exact mul_dvd_mul (h a (Multiset.mem_cons_self a s))
      (ih fun x hx => h x (Multiset.mem_cons_of_mem hx))

/-- Lemma 5.4 applied at a root of an irreducible factor: if all minors vanish at a root of
the irreducible `π ∈ ℚ[z]`, then `π ∣ z` or `π ∣ z^n - 1` for some `n > 0`. -/
lemma irreducible_dvd_of_minors (π : ℚ[X]) (hπ : Irreducible π)
    (h : ∀ a : Fin ℓ → ℕ, Admissible a → π ∣ toQ (minor ℓ a)) :
    π ∣ X ∨ ∃ n : ℕ, 0 < n ∧ π ∣ X ^ n - 1 := by
  have : Fact (Irreducible π) := ⟨hπ⟩
  have hae : ∀ f : ℚ[X], aeval (AdjoinRoot.root π) f = AdjoinRoot.mk π f :=
    fun f => AdjoinRoot.aeval_eq f
  have hzero : ∀ f : ℚ[X], π ∣ f → aeval (AdjoinRoot.root π) f = 0 := fun f hf => by
    rw [hae, AdjoinRoot.mk_eq_zero]; exact hf
  have hdet : ∀ a : Fin ℓ → ℕ, Admissible a → (evalMat (AdjoinRoot.root π) a).det = 0 := by
    intro a ha
    rw [← aeval_minor, ← aeval_map_algebraMap ℚ, algebraMap_int_eq]
    exact hzero _ (h a ha)
  obtain ⟨c, hc, hrel⟩ := exists_kernel_of_minors_eq_zero (AdjoinRoot.root π) hdet
  by_cases hθ : AdjoinRoot.root π = 0
  · left
    rw [← AdjoinRoot.mk_eq_zero, ← hae, aeval_X]
    exact hθ
  · right
    obtain ⟨n, hn, hθn⟩ := pow_eq_one_of_relation hθ c hc hrel
    refine ⟨n, hn, ?_⟩
    rw [← AdjoinRoot.mk_eq_zero, ← hae]
    simp [hθn]

/-- The data extracted from the ideal of minors. -/
theorem exists_minor_data (ℓ : ℕ) :
    ∃ (F : Finset (Fin ℓ → ℕ)) (g : ℤ[X]) (N : ℤ) (h : (Fin ℓ → ℕ) → ℤ[X])
      (T : Finset ℚ[X]) (sel : ℚ[X] → Fin ℓ → ℕ) (V : ℚ[X] → ℤ[X]) (L e : ℕ),
      (∀ a ∈ F, Admissible a) ∧ stdRows ℓ ∈ F ∧ g.Monic ∧ N ≠ 0 ∧
      (∀ a, Admissible a → minor ℓ a = g * h a) ∧
      (∀ t ∈ T, sel t ∈ F) ∧ ∑ t ∈ T, V t * h (sel t) = C N ∧
      0 < L ∧ g ∣ (X * (X ^ L - 1)) ^ e := by
  classical
  -- the ideal of all minors and its generator
  set φ : (Fin ℓ → ℕ) → ℚ[X] := fun a => toQ (minor ℓ a) with hφ
  set A : Set (Fin ℓ → ℕ) := {a | Admissible a} with hA
  set I : Ideal ℚ[X] := Ideal.span (φ '' A) with hI
  set g₀ := Submodule.IsPrincipal.generator I with hg₀
  have hIg : I = Ideal.span {g₀} := (Ideal.span_singleton_generator I).symm
  have hg₀mem : g₀ ∈ I := Submodule.IsPrincipal.generator_mem I
  have hdvd₀ : ∀ a ∈ A, g₀ ∣ φ a := by
    intro a ha
    have : φ a ∈ I := Ideal.subset_span ⟨a, ha, rfl⟩
    rwa [hIg, Ideal.mem_span_singleton] at this
  have hstdφ : φ (stdRows ℓ) ≠ 0 := (minor_stdRows_monic.map _).ne_zero
  have hg₀0 : g₀ ≠ 0 := by
    intro h0
    apply hstdφ
    have := hdvd₀ _ stdRows_admissible
    rwa [h0, zero_dvd_iff] at this
  -- finitely many minors generate `I` (Noetherianity)
  obtain ⟨T₀, hT₀, hgT₀⟩ := Submodule.mem_span_finite_of_mem_span hg₀mem
  obtain ⟨F₀, hF₀, hF₀T⟩ := Finset.subset_set_image_iff.1 hT₀
  set F := insert (stdRows ℓ) F₀ with hF
  have hFA : ∀ a ∈ F, Admissible a := by
    intro a ha
    rcases mem_insert.1 ha with rfl | ha
    · exact stdRows_admissible
    · exact hF₀ ha
  set T := F.image φ with hT
  have hgT : g₀ ∈ Ideal.span (T : Set ℚ[X]) := by
    refine Submodule.span_mono ?_ hgT₀
    rw [← hF₀T, hT]
    exact coe_subset.2 (image_subset_image (subset_insert _ _))
  -- the monic generator `g₁` and its integral model `g`
  set g₁ := g₀ * C (leadingCoeff g₀)⁻¹ with hg₁
  have hg₁monic : g₁.Monic := monic_mul_leadingCoeff_inv hg₀0
  have hg₁g₀ : g₁ ∣ g₀ := by
    refine ⟨C (leadingCoeff g₀), ?_⟩
    rw [hg₁, mul_assoc, ← C_mul, inv_mul_cancel₀ (leadingCoeff_ne_zero.2 hg₀0), C_1, mul_one]
  have hdvd₁ : ∀ a ∈ A, g₁ ∣ φ a := fun a ha => hg₁g₀.trans (hdvd₀ a ha)
  have hg₁T : g₁ ∈ Ideal.span (T : Set ℚ[X]) := Ideal.mul_mem_right _ _ hgT
  obtain ⟨g, hg⟩ := IsIntegrallyClosed.eq_map_mul_C_of_dvd ℚ minor_stdRows_monic
    (hdvd₁ _ stdRows_admissible)
  rw [hg₁monic.leadingCoeff, C_1, mul_one, algebraMap_int_eq] at hg
  have hgmonic : g.Monic :=
    monic_of_injective (RingHom.injective_int (Int.castRingHom ℚ)) (hg ▸ hg₁monic)
  have hgg₁ : toQ g = g₁ := by rw [toQ_apply]; exact hg
  -- every minor is `g · h`
  set h : (Fin ℓ → ℕ) → ℤ[X] := fun a => minor ℓ a /ₘ g with hh
  have hgh : ∀ a, Admissible a → minor ℓ a = g * h a := by
    intro a ha
    have hd : g ∣ minor ℓ a := dvd_of_toQ_dvd hgmonic (by rw [hgg₁]; exact hdvd₁ a ha)
    have := modByMonic_add_div (minor ℓ a) g
    rw [(modByMonic_eq_zero_iff_dvd hgmonic).2 hd, zero_add] at this
    exact this.symm
  -- Bézout's identity in `ℚ[z]`
  obtain ⟨u, -, hu⟩ := Submodule.mem_span_finset.1 hg₁T
  have hsel : ∀ t ∈ T, ∃ a ∈ F, φ a = t := fun t ht => by
    obtain ⟨a, ha, rfl⟩ := mem_image.1 ht; exact ⟨a, ha, rfl⟩
  choose! sel hselF hselφ using hsel
  have ht' : ∀ t ∈ T, t = g₁ * toQ (h (sel t)) := by
    intro t ht
    calc t = φ (sel t) := (hselφ t ht).symm
      _ = toQ (g * h (sel t)) := by rw [hφ]; simp only; rw [← hgh _ (hFA _ (hselF t ht))]
      _ = g₁ * toQ (h (sel t)) := by rw [map_mul, hgg₁]
  have hone : ∑ t ∈ T, u t * toQ (h (sel t)) = 1 := by
    have hexp : g₁ = g₁ * ∑ t ∈ T, u t * toQ (h (sel t)) := by
      conv_lhs => rw [← hu]
      rw [mul_sum]
      refine sum_congr rfl fun t ht => ?_
      calc u t • t = u t * t := smul_eq_mul _ _
        _ = u t * (g₁ * toQ (h (sel t))) := congrArg _ (ht' t ht)
        _ = g₁ * (u t * toQ (h (sel t))) := by ring
    have := hexp
    rw [eq_comm, mul_eq_left₀ hg₁monic.ne_zero] at this
    exact this
  -- clearing denominators
  obtain ⟨d, hd, hv⟩ := exists_common_denom T u
  choose! V hV using hv
  have hbez : ∑ t ∈ T, V t * h (sel t) = C d := by
    apply toQ_injective
    have : toQ (∑ t ∈ T, V t * h (sel t)) = C (d : ℚ) * ∑ t ∈ T, u t * toQ (h (sel t)) := by
      rw [map_sum, mul_sum]
      refine sum_congr rfl fun t ht => ?_
      rw [map_mul, hV t ht]
      ring
    rw [this, hone, mul_one, toQ_C]
  -- the roots of `g₁`: every irreducible factor divides `z` or `z^n - 1`
  have hfac : ∀ π ∈ UniqueFactorizationMonoid.normalizedFactors g₁,
      π ∣ X ∨ ∃ n : ℕ, 0 < n ∧ π ∣ X ^ n - 1 := by
    intro π hπ
    refine irreducible_dvd_of_minors (ℓ := ℓ) π
      (UniqueFactorizationMonoid.irreducible_of_normalized_factor π hπ) fun a ha => ?_
    exact (UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hπ).trans (hdvd₁ a ha)
  choose! nπ hnπ using fun (π : ℚ[X]) hπ =>
    (show ∃ n : ℕ, 0 < n ∧ (π ∣ X ∨ π ∣ (X ^ n - 1 : ℚ[X])) by
    rcases hfac π hπ with h1 | ⟨n, hn, h2⟩
    · exact ⟨1, one_pos, Or.inl h1⟩
    · exact ⟨n, hn, Or.inr h2⟩)
  set s := UniqueFactorizationMonoid.normalizedFactors g₁ with hs
  set L := ∏ π ∈ s.toFinset, nπ π with hL
  have hLpos : 0 < L := prod_pos fun π hπ => (hnπ π (Multiset.mem_toFinset.1 hπ)).1
  have hπF : ∀ π ∈ s, π ∣ X * (X ^ L - 1) := by
    intro π hπ
    rcases (hnπ π hπ).2 with h1 | h2
    · exact h1.mul_right _
    · refine (h2.trans ?_).mul_left _
      obtain ⟨m, hm⟩ : nπ π ∣ L := dvd_prod_of_mem _ (Multiset.mem_toFinset.2 hπ)
      rw [hm, pow_mul]
      have := sub_dvd_pow_sub_pow (X ^ nπ π : ℚ[X]) 1 m
      rwa [one_pow] at this
  have hg₁F : g₁ ∣ (X * (X ^ L - 1)) ^ Multiset.card s :=
    (UniqueFactorizationMonoid.prod_normalizedFactors hg₁monic.ne_zero).symm.dvd.trans
      (multiset_prod_dvd_pow _ s hπF)
  have hgF : g ∣ (X * (X ^ L - 1)) ^ Multiset.card s := by
    refine dvd_of_toQ_dvd hgmonic ?_
    rw [hgg₁]
    simpa [toQ_apply] using hg₁F
  exact ⟨F, g, d, h, T, sel, V, L, Multiset.card s, hFA, mem_insert_self _ _, hgmonic, hd,
    hgh, hselF, hbez, hLpos, hgF⟩

end RestrictedPolynomials

end
